version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/eslint/*"
      - "/vscode/*"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
      exclude:
        - "@zemd/*"
    versioning-strategy: "increase"
    open-pull-requests-limit: 10
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    groups:
      devcontainer-images:
        patterns:
          - "*"

  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    groups:
      devcontainer-features:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"
