name: Scorecard

permissions: {}

on:
  push:
    branches:
      - main
  branch_protection_rule:
  schedule:
    - cron: "41 5 * * 1"

concurrency:
  group: scorecard-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scorecard:
    name: Scorecard
    uses: zemd/js/.github/workflows/shared-scorecard.yml@fb41af590e525c7846a8dce0286fa69ac89171f7 # v4.0.1
    permissions:
      contents: read # checkout the repository for analysis
      actions: read # inspect workflow runs for dangerous patterns
      security-events: write # upload results to code scanning
      id-token: write # publish results to the OpenSSF API
