name: zizmor

permissions: {}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "13 6 * * 1"
  workflow_dispatch:

concurrency:
  group: zizmor-${{ github.ref }}
  cancel-in-progress: true

jobs:
  zizmor:
    name: zizmor
    uses: zemd/js/.github/workflows/shared-zizmor.yml@90cbb33b807a57692d0b86fb24e41c003e440c8e # v4.0.4
    permissions:
      contents: read
