name: CI

permissions: {}

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    uses: zemd/js/.github/workflows/shared-ci.yml@90cbb33b807a57692d0b86fb24e41c003e440c8e # v4.0.4
    permissions:
      contents: read
    with:
      report-change-intents: true
      dependency-review-severity: high
